# Generated by Django 3.0.8 on 2020-07-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_blog_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='content',
        ),
    ]
