# Generated by Django 3.0.8 on 2020-07-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200724_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='duedate',
            field=models.DateTimeField(null=True),
        ),
    ]
